services:
  postgres:
    container_name: postgres_go_product
    image: postgres:16.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_pass
      - PGDATA=/data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - 57800:57800